name = "weather-api"
account_id = "c05ca05a196a72ce05061da69b0170f1"
main = "src/index.ts"
compatibility_date = "2025-03-20"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "WEATHER_CACHE", class_name = "WeatherCache" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WeatherCache"]

[vars]
CORS_ORIGIN = "https://weather-app-6v5.pages.dev"
